export const LEADS_API = {
  CREATE: "/crm/leads",
  LIST: "/crm/leads",
  CHECK_PHONE: (phone: string) => `/crm/leads/check-phone/${encodeURIComponent(phone)}`,
  GET: (id: string) => `/crm/leads/${id}`,
  UPDATE: (id: string) => `/crm/leads/${id}`,
  DELETE: (id: string) => `/crm/leads/${id}`,
  PIPELINES: {
    LIST: "/crm/pipelines",
    CREATE: "/crm/pipelines",
    GET: (id: string) => `/crm/pipelines/${id}`,
    VIEW: (id: string) => `/crm/pipelines/${id}/view`,
    UPDATE: (id: string) => `/crm/pipelines/${id}`,
    DELETE: (id: string) => `/crm/pipelines/${id}`,
  },
  EXPORT: "/crm/leads/export",
  STAGE: (id: string) => `/crm/leads/${id}/stage`,
  ACTIVITIES: (id: string) => `/crm/leads/${id}/activities`,
  BULK_PIPELINE: "/crm/leads/bulk-pipeline",
  BULK_STAGE: "/crm/leads/bulk-stage",
  ASSIGN_COUNSELOR: "/crm/leads/assign-counselor",
  DASHBOARD: "/crm/dashboard",
  DASHBOARD_EXPORT: "/crm/dashboard/export",
  ASSIGN_CERTIFICATE: (id: string) => `/crm/leads/${id}/certificate`,
  ADD_TO_PIPELINES: "/crm/leads/add-to-pipelines",
};
