import {
  LayoutDashboard,
  ChartLine,
  GraduationCap,
  FolderTree,
  Users,
  ListChecks,
  Award,
  UserPlus,
  ReceiptText,
  Target,
  Settings,
  ShieldCheck,
  Play,
  FileText,
  AlignLeft,
  CircleCheckBig,
  Briefcase,
  Wallet,
  FileCheck2,
  Flag,
  Clock,
  Tag,
  UsersRound,
  ClipboardList,
  KanbanSquare,
  CreditCard,
  Undo2,
  UserCog,
  CalendarDays,
  Bell,
  Home,
  Newspaper,
  Mail,
  Heart,
  Plus,
  SlidersHorizontal,
  GitBranch,
  Coins,
  LayoutTemplate,
  FileSearch,
  Megaphone,
  MessageSquareQuote,
  PenTool,
  ScrollText,
  Link2,
  type LucideIcon,
} from "lucide-react";

/**
 * Single source of truth mapping the string icon names stored in our nav /
 * option data to real lucide components — keeps data files JSX-free.
 */
export const ICONS: Record<string, LucideIcon> = {
  LayoutDashboard,
  ChartLine,
  GraduationCap,
  FolderTree,
  Users,
  ListChecks,
  Award,
  UserPlus,
  ReceiptText,
  Target,
  Settings,
  ShieldCheck,
  Play,
  FileText,
  AlignLeft,
  CircleCheckBig,
  Briefcase,
  Wallet,
  FileCheck2,
  Flag,
  Clock,
  Tag,
  UsersRound,
  ClipboardList,
  KanbanSquare,
  CreditCard,
  Undo2,
  UserCog,
  CalendarDays,
  Bell,
  Home,
  Newspaper,
  Mail,
  Heart,
  Plus,
  SlidersHorizontal,
  GitBranch,
  Coins,
  LayoutTemplate,
  FileSearch,
  Megaphone,
  MessageSquareQuote,
  PenTool,
  ScrollText,
  Link2,
};

export function getIcon(name: string): LucideIcon {
  return ICONS[name] ?? LayoutDashboard;
}
