/**
 * Centralized route paths for maintainability and type-safe navigation.
 */
export const ROUTES = {
  HOME: "/",
  ABOUT: "/about",
  BECOME_INSTRUCTOR: "/become-instructor",
  CONTACT: "/contact",
  COURSES: "/courses",
  COURSE_DETAIL: (id: string) => `/courses/${id}`,
  CATEGORY: (slug: string) => `/category/${slug}`,
  SEARCH: "/search",
  LOGIN: "/auth/login",
  SIGNUP: "/auth/signup",
  FORGOT_PASSWORD: "/auth/forgot-password",
  ACCEPT_INVITATION: "/auth/accept-invitation",
  TERMS: "/terms",
  PRIVACY: "/privacy",

  ADMIN: {
    DASHBOARD: "/admin/dashboard",
    REPORTS: "/admin/reports",
    CRM_LEAD_DASHBOARD: "/admin/crm/dashboard",
    CRM_LEADS: "/admin/crm/leads",
    CRM_LEAD_NEW: "/admin/crm/leads/new",
    CRM_LEAD: (id: string) => `/admin/crm/leads/${id}`,
    CRM_LEAD_ADD_TO_GROUP: (id: string) =>
      `/admin/crm/leads/${id}/add-to-group`,
    CRM_PIPELINE: "/admin/crm/pipeline",
    CRM_PIPELINES: "/admin/crm/pipelines",
    /** Installment schedules — overdue, upcoming, collected installments. */
    CRM_PAYMENT_TRACKING: "/admin/crm/payment-tracking",
    CRM_SETTINGS: "/admin/crm/settings",
    COURSES: "/admin/courses",
    COURSES_REGISTRATIONS: "/admin/courses/registrations",
    COURSE: (id: string) => `/admin/courses/${id}`,
    COURSE_EDIT: (id: string) => `/admin/courses/${id}/edit`,
    COURSE_SEO: (id: string) => `/admin/courses/${id}/seo`,
    LMS_MANAGEMENT: "/admin/lms",
    LMS_COURSES: "/admin/lms",
    LMS_COURSE: (id: string) => `/admin/lms/${id}`,
    LMS_SETTINGS: "/admin/lms/settings",
    QUIZZES: "/admin/quizzes",
    ASSIGNMENTS: "/admin/assignments",
    USERS: "/admin/users",
    USER_OVERVIEW: (id: string) => `/admin/users/${id}`,
    USERS_INVITE: "/admin/users/invite",
    USERS_ROLES: "/admin/users/roles",
    USERS_ACTIVITY_LOG: (id: string) => `/admin/users/${id}/activity-log`,
    STUDENTS: "/admin/students",
    STUDENT_OVERVIEW: (id: string) => `/admin/students/${id}`,
    TRANSACTIONS: "/admin/transactions",
    /** Ledger quick views (aligned with CRM payments filter tabs). */
    TRANSACTIONS_PRESET: (preset: string) =>
      `/admin/transactions?preset=${encodeURIComponent(preset)}`,
    TRANSACTIONS_REFUNDS: "/admin/transactions/refunds",
    TRANSACTIONS_PAYOUTS: "/admin/transactions/payouts",
    TRANSACTION_DETAIL: (id: string) => `/admin/transactions/${id}`,
    INVOICES: "/admin/crm/invoices",
    INVOICES_NEW: "/admin/crm/invoices/new",
    INVOICES_NEW_PAID: "/admin/crm/invoices/new?paid=1",
    INVOICES_DRAFTS: "/admin/crm/invoices?status=draft",
    INVOICES_SENT: "/admin/crm/invoices?status=sent",
    INVOICE: (id: string) => `/admin/crm/invoices/${id}`,
    GROUPS: "/admin/crm/groups",
    GROUPS_SETTINGS: "/admin/crm/groups/settings",
    GROUP: (id: string) => `/admin/crm/groups/${id}`,
    INSTRUCTORS: "/admin/instructors",
    INSTRUCTOR_NEW: "/admin/instructors/add",
    INSTRUCTOR: (id: string) => `/admin/instructors/${id}`,
    EVENTS: "/admin/events",
    SETTINGS: "/admin/settings",
    WHATSAPP_TEMPLATES: "/admin/settings/whatsapp-templates",
    WHATSAPP_TEMPLATE_EDIT: "/admin/settings/whatsapp-templates/edit",
    NOTIFICATIONS: "/admin/notifications",
  },

  EMPLOYEE: {
    DASHBOARD: "/employee/dashboard",
    CRM_LEADS: "/employee/crm/leads",
    CRM_LEAD_NEW: "/employee/crm/leads/new",
    CRM_LEAD: (id: string) => `/employee/crm/leads/${id}`,
    CRM_PIPELINE: "/employee/crm/pipeline",
    CRM_GROUPS: "/employee/crm/groups",
    NOTIFICATIONS: "/employee/notifications",
    PROFILE: "/employee/profile",
    SETTINGS: "/employee/settings",
  },

  INSTRUCTOR: {
    DASHBOARD: "/instructor/dashboard",
    COURSES: "/instructor/courses",
    COURSE_NEW: "/instructor/courses/new",
    COURSE: (id: string) => `/instructor/courses/${id}`,
    COURSE_EDIT: (id: string) => `/instructor/courses/${id}/edit`,
    QUIZZES: "/instructor/quizzes",
    QUIZ_NEW: "/instructor/quizzes/new",
    QUIZ: (id: string) => `/instructor/quizzes/${id}`,
    EVENTS: "/instructor/events",
    EVENTS_MANAGE: "/instructor/events/manage",
    EVENT_NEW: "/instructor/events/new",
    ANALYTICS: "/instructor/analytics",
    EARNINGS: "/instructor/earnings",
    PROFILE: "/instructor/profile",
    SETTINGS: "/instructor/settings",
  },

  STUDENT: {
    DASHBOARD: "/student/dashboard",
    COURSES: "/student/courses",
    COURSE_OVERVIEW: (id: string) => `/student/courses/${id}`,
    COURSE_ROADMAP: (id: string) => `/student/courses/${id}`,
    COURSE_LESSON: (courseId: string, lessonId: string) =>
      `/student/courses/${courseId}/lesson/${lessonId}`,
    COURSE_QUIZ: (courseId: string, quizId: string) =>
      `/student/courses/${courseId}/quiz/${quizId}`,
    SCHEDULE: "/student/schedule",
    GRADES: "/student/grades",
    ASSIGNMENTS: "/student/assignments",
    ASSIGNMENT_DETAIL: (id: string) => `/student/assignments/${id}`,
    CERTIFICATES: "/student/certificates",
    TRANSCRIPT: "/student/transcript",
    TRANSCRIPTS: "/student/transcripts",
    FAVORITES: "/student/favorites",
    BILLING: "/student/billing",
    INSTALLMENTS: "/student/installments",
    VERIFICATION_STATUS: "/student/verification-status",
    PAYMENT_METHODS: "/student/payment-methods",
    CHECKOUT: "/student/checkout",
    PROFILE: "/student/profile",
    SETTINGS: "/student/settings",
    NOTIFICATIONS: "/student/notifications",
  },
} as const;
